language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk11

sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

script:
  - (test $TRAVIS_SCALA_VERSION == "2.13.1" && sbt ++$TRAVIS_SCALA_VERSION fmtCheck) || test $TRAVIS_SCALA_VERSION == "2.12.10"
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -Dfs2.test.travis testJVM
  - (test $TRAVIS_SCALA_VERSION == "2.12.10" && sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 -J-Xms2g -J-Xmx2g) || test $TRAVIS_SCALA_VERSION == "2.13.1"
