language: scala

scala:
  - 2.13.3

jdk:
  - openjdk11

sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - graphviz

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

branches:
  except:
    - /^pr\..*/

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: sbt ++$TRAVIS_SCALA_VERSION test
    - stage: "Integraton tests"
      before_script: docker-compose up
      name: "Integraton test"
      script: sbt ++$TRAVIS_SCALA_VERSION it:test
      after_success: docker-compose down

