language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk11

sudo: false
addons:
  apt:
    packages:
      - graphviz

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - scala: 2.12.11 # Remember to update this in build.sbt, too.
      install:
        - pip install --user codecov
      script:
        - sbt ++$TRAVIS_SCALA_VERSION validateJVM &&
          sbt ++$TRAVIS_SCALA_VERSION clean
      after_success:
        - codecov

    - scala: 2.13.1 # Remember to update this in build.sbt, too.
      script:
        - sbt ++$TRAVIS_SCALA_VERSION testJVM213 &&
          sbt ++$TRAVIS_SCALA_VERSION testJS213
